<a href="https://colab.research.google.com/github/PrernaKumari147/NeuralNetwork/blob/main/700749909_ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prerna Kumari

700749909


1.Create a class Employee and then do the following:                                     



• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [6]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Ankit", "Singh", 100000, "Manager")
employee2 = Employee("Prerna", "Kumari", 90000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Ankit", "Singh", 75000, "Finance")
fulltime_employee2 = FulltimeEmployee("Prerna", "Kumari", 60000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)



Average Salary for Employees: 47500.0
Average Salary for Fulltime Employees: 33750.0


2.Numpy


Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)


In [27]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [ 3.27704775  4.78704088  1.82303598 14.46804878 15.97290304  7.89883008
  6.82570416  2.75674058  6.36182302 18.9231247   6.43044053  1.65350136
 14.49749719 19.33120072  5.14394167  3.16856958 15.04669495 16.12608567
  3.83989719  2.78043491]


In [28]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[ 3.27704775  4.78704088  1.82303598 14.46804878 15.97290304]
 [ 7.89883008  6.82570416  2.75674058  6.36182302 18.9231247 ]
 [ 6.43044053  1.65350136 14.49749719 19.33120072  5.14394167]
 [ 3.16856958 15.04669495 16.12608567  3.83989719  2.78043491]]


In [29]:

# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 3.27704775  4.78704088  1.82303598 14.46804878  0.        ]
 [ 7.89883008  6.82570416  2.75674058  6.36182302  0.        ]
 [ 6.43044053  1.65350136 14.49749719  0.          5.14394167]
 [ 3.16856958 15.04669495  0.          3.83989719  2.78043491]]
